#+TITLE: Architecture of the system

* The goals

The tasks I want the robot system to fulfill are:
- Have a tight control loop with low latency reaction to changes in input
- Allow remote control via an HTTP server.
- Stream live video from the camera over a websocket.

* The goals in isolation

** Control loop

A robot control loop consists of:
- Read input from sensors
- Process input in some way
- Send output to the actuators

The latency of the processing should be as low as possible to minimise the
reaction time between a change in input and a corresponding change in output.
The higher the latency the slower the robot's maximum driving speed, for
example, because otherwise it couldn't react to in time. This is already limited
by the reaction times of motors and the speed of the sensors.

** Remote control via HTTP

The HTTP server serves a frontend and needs to somehow control the loop

** Camera streaming

The needs to call out to FFMpeg, and get debug data somehow.

* Combining them

Combining the goals would be simple if not for the control loops low latency
requirement. If this didn't exist, then we would just need to process a frame
and then send it to be streamed. But this is slow, and so I want to separate out
the image processing from the other sensing tasks. This causes problems with
getting the data produced by the

* Solution

Have
